//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOT.DAL.Cluster
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cluster
    {
        public System.Guid ClusterID { get; set; }
        public string ClusterName { get; set; }
        public string NodeClusterCatalog { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
    }
}
